version: '3.6'

services:
  app:
    build:
      context: ./..
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      PG_URL: postgres://postgres:postgres@postgres:5432/lw
    networks:
      - lw

  postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-lw}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - lw

networks:
  lw:
    driver: bridge

volumes:
  postgres: