version: '3.6'

services:
  postgres:
    image: postgres:11.4-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lw
      - PGDATA=/data/postgres
    volumes:
      - lwpostgres:/data/postgres
    networks:
      - lw

  app:
    build:
      context: ./..
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      PG_DSN: postgres://postgres:postgres@postgres:5432/lw
    command: ["./wait-for-it.sh", "postgres:5432", "--", "./main"]
    networks:
      - lw

networks:
  lw:
    driver: bridge

volumes:
  lwpostgres: